# Generated by Django 5.2.5 on 2025-09-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financeitemcategory',
            name='category',
        ),
        migrations.AddField(
            model_name='financeitemcategory',
            name='name',
            field=models.CharField(default='test', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
